### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by blerude** [jonenzl/bwa-u4-feature-request#1]
Grade: Exceeds Expectations

Great job on this proposal! You've suggested and laid out a plan for not one, not two, but three separate new features for Jammming, and each is a great addition to the app. You've identified three ways in which the Jammming app as it is does not deliver what other apps of this kind do--features that users would expect--and created solutions to each. For your 'Enter' key proposal, I think you've identified the quickest and cleanest way to solve the problem, and I appreciate you including code snippets. For your album artwork and music sample issues, great job digging more into the Spotify API. The music sample can be difficult because it's hard to know what to do with the url that makes the sample easily accessible to users without having to copy or paste it into a browser, but your suggestion to put an <audio> element in the render function solves that. 

Overall, fantastic job here! I hope that you continue implement this idea and bring it to reality. Congratulations!

**Comment by jonenzl** [comment]
Thank you
